# Swiss Roll GP-LVM SSVI Configuration - Higher Dimensional Latent Space

# general
device: cuda          # "cuda", "cpu", or "auto"
debug: false          # print tensor shapes on first outer loop

# dataset configuration
dataset:
  type: swiss_roll     # "oil" or "swiss_roll" 
  n_samples: 1500      # number of Swiss Roll samples to generate
  noise: 0.05          # lower noise level for cleaner patterns
  random_state: 123    # different random seed

# learning rates
lr:
  x:   1e-3           # Adam for {mu_x, log_s2x}
  hyp: 1e-3           # Adam for kernel hypers + Z
  alpha: 5e-3         # Adam for alpha

# training schedule
training:
  batch_size: 128     # B
  total_iters: 800    # more iterations for higher dimensional case
  inner_iters:
    start:  50        # INNER0 (first   inner_switch iters)
    after:  40        # INNER  (after   inner_switch)
    switch: 100       # iteration number to switch

# init mu_x, log_sigma2_x
init_latent_dist:
  method: default
  custom_path: ""

# inducing points
inducing:
  n_inducing: 64                 # number of inducing points
  selection: perm       # strategy: "perm" or "kmeans"
  seed: 42              # fixed seed

# numerical stability
jitter:  5e-6
max_exp: 60.0

# SVI step size rho(t) = (t0 + t)^(-k)
rho:
  t0: 100.0
  k:  0.6

# model structure
q_latent:   6         # Q=6 for testing higher dimensional latent space

# additional
init_signal_to_noise_ratio: 1.0
num_u_samples_per_iter: 2 