device: auto
debug: false

# dataset configuration  
dataset:
  type: oil            # "oil" or "swiss_roll"

optimizer:
  lr: 0.01

training:
  batch_size: 100
  total_iters: 10000
  smoke_test: false

inducing:
  n_inducing: 25                 # number of inducing points
  selection: perm       # strategy: "perm" or "kmeans"
  seed: 19              # fixed seed (can be null if not needed)

init_latent_dist:
  method: default
  custom_path: null

q_latent:   12        # Q  (= D for the oil data)