# Quick Test Cross Validation Configuration for LVMOGP-SSVI
# Minimal parameters for testing the CV pipeline

gp_ssvi:
  # Device settings
  device: cpu                # Use CPU for quick testing
  debug: false

  # Dataset configuration (required field)
  dataset:
    type: oil               # Using oil dataset for biological experiments
    n_samples: 1000         # Not used for real data but required field
    noise: 0.1              # Not used for real data but required field
    random_state: null      # Not used for real data

  # Learning rates (required by GPSSVIConfig)
  lr:
    x: 1e-3                 # Learning rate for latent variables H
    hyp: 1e-3               # Learning rate for hyperparameters
    alpha: 5e-3             # Learning rate for length scales

  # Training settings (required by GPSSVIConfig)
  training:
    batch_size: 100         # Smaller batch size for testing
    total_iters: 50         # Much fewer iterations for testing
    inner_iters:
      start: 10             # Inner iterations for first epochs
      after: 5              # Inner iterations after switch
      switch: 20            # When to switch inner iteration count

  # Latent variable initialization (required by GPSSVIConfig)
  init_latent_dist:
    method: default         # Use default random initialization
    custom_path: ""

  # Inducing points settings (required by GPSSVIConfig)
  inducing:
    n_inducing: 16          # Reduced for speed
    selection: perm         # Random permutation selection
    seed: 19                # Seed for inducing point initialization

  # Numerical stability (required by GPSSVIConfig)
  jitter: 5e-6
  max_exp: 60.0

  # SVI step size schedule (required by GPSSVIConfig)
  rho:
    t0: 100.0              # Initial step size parameter
    k: 0.6                 # Decay rate

  # Model architecture (required by GPSSVIConfig)
  q_latent: 4                         # Reduced latent dimension for speed
  init_signal_to_noise_ratio: 1.0     # Initial signal-to-noise ratio
  num_u_samples_per_iter: 1           # Number of U samples per iteration

# Cross Validation specific parameters
cv:
  # Minimal seeds for quick testing
  seeds: [0, 1]
  
  # Just a few training percentages for quick test
  train_percentages: [30, 60, 90]

# Experimental metadata
experimental:
  description: "Quick test of cross validation pipeline"
  purpose: "Verify CV implementation before full run"
  
  # Note: Output will have columns:
  # ['no test points', 'no train points', 'lvm_ssvi_test_RMSE', 'lvm_ssvi_test_NLPD', 
  #  'lvm_ssvi_test_RMSE_z', 'lvm_ssvi_test_NLPD_z', 'lvm_ssvi_train_RMSE', 
  #  'lvm_ssvi_train_NLPD', 'lvm_ssvi_train_RMSE_z', 'lvm_ssvi_train_NLPD_z', 
  #  'seed', 'pct_train', 'param'] 